# Cloudflare Pages configuration
name = "workfree"
compatibility_date = "2024-01-01"

[build]
command = "bun run build"
cwd = "."

[build.upload]
format = "service-worker"

# Environment variables (set in Cloudflare dashboard)
# DATABASE_URL
# STRIPE_SECRET_KEY
# PUBLIC_STRIPE_PUBLISHABLE_KEY
# STRIPE_WEBHOOK_SECRET
# RESEND_API_KEY
# PUBLIC_APP_URL

# D1 Database binding (if using Cloudflare D1)
# [[d1_databases]]
# binding = "DB"
# database_name = "workfree-prod"
# database_id = "your-database-id"

# KV namespace for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-id"

# Analytics (optional)
# [analytics_engine_datasets]
# binding = "ANALYTICS"

