name: workfree
description: WorkFree - VR Training Platform Mobile App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.0
  riverpod: ^2.4.0
  riverpod_generator: ^2.3.0

  # Networking
  http: ^1.1.0
  dio: ^5.3.0
  retrofit: ^4.0.0

  # Local Storage
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  # UI/UX
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.6.0

  # Authentication
  firebase_auth: ^4.10.0
  firebase_core: ^2.24.0
  google_sign_in: ^6.1.0

  # Database
  firebase_firestore: ^4.13.0
  firebase_storage: ^11.2.0

  # Analytics
  firebase_analytics: ^10.7.0
  mixpanel_flutter: ^2.3.0

  # Payments
  stripe_flutter: ^10.0.0
  in_app_purchase: ^3.1.0

  # Notifications
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^16.1.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.0.0
  equatable: ^2.0.0
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0

  # VR/AR
  arcore_flutter_plugin: ^0.0.5
  arkit_flutter_plugin: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  riverpod_generator: ^2.3.0
  retrofit_generator: ^7.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

